#!/usr/bin/env bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $script_dir/ut-common
command=$0

function addDataView() {
  echo "adding data view for $1"

  body=`hjson -c << END_BODY
  {
    override: false
    data_view: {
      title: "$1"
      name: "$1"
    }
  }
END_BODY`

  res=`curl -sfX POST $KB_URL/api/data_views/data_view \
    -H 'elastic-api-version: 2023-10-31' \
    -H 'kbn-xsrf: true' \
    -H 'Content-Type: application/json' \
    -d "$body"`
  if [ $? -ne 0 ]; then errorExit "error creating data view: $res"; fi
}

addDataView ".kibana"
addDataView ".kibana_task_manager"
addDataView ".kibana_alerting_cases"
addDataView ".kibana_analytics"
addDataView ".kibana-event-log-*"
