#!/usr/bin/env bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $script_dir/ut-common
command=$0

ruleParams=`hjson -c << END_PARAMS
{
  index:               ["es-apm-sys-sim"], 
  timeField:           "@timestamp", 
  aggType:             "avg", 
  aggField:            "system.cpu.total.norm.pct",
  groupBy:             "top",
  termSize:            100,
  termField:           "host.name.keyword",
  timeWindowSize:      3, 
  timeWindowUnit:      "s", 
  thresholdComparator: ">", 
  threshold:           [0.5]
}
END_PARAMS`

ruleId=`$script_dir/kb-create-rule .index-threshold "$ruleParams"`
if [ $? -ne 0 ]; then errorExit "error creating rule: $ruleRes"; fi
echo "created rule $ruleId"
